### ISSUE TITLE
Criar novo S3 Amazon para fazer um ambiente de testes do projeto antes de entrar em produção

### ISSUE THREAD

**Issue by isamaues** [BrieflyPlanningPokerES23/BrieflyPlanningPoker#10]
Na amazon é limitado o número de máquinas por pacote, se mais uma pessoa tiver o plano conseguimos criar um ambiente de testes.

**Comment by isamaues** [comment]
Na amazon é limitado o número de máquinas por pacote, se mais uma pessoa tiver o plano conseguimos criar um ambiente de testes.

**Comment by jplukas** [comment]
Boa ideia, precisamos conversar sobre isso. Para isso precisamos de #8
