### ISSUE TITLE
Gerenciamento de tokens

### ISSUE THREAD

**Issue by jplukas** [BrieflyPlanningPokerES23/BrieflyPlanningPoker#14]
Hoje, a autenticação que existe para um usuário realizar qualquer atividade no app só verifica se um token existe e é "válido" sintaticamente, sem fazer qualquer consulta no banco de dados para verificar se o token realmente existe (i.e. se o usuário realmente está logado), e na hora do login, a aplicação também somente devolve um token válido para ser armazenado no gerenciamento de sessão do navegador (e depois usado em requisições posteriores), também sem qualquer alteração no banco de dados.

Diante disso, precisamos implementar os seguintes processos:

- [x] #19
- [x] #20
- [x] #21

**Comment by isamaues** [comment]
Não há nenhuma componente no front end para fazer logout, nem na api tem um endpoint para isso

**Comment by jplukas** [comment]
Após uma certa análise, concluí que não faz sentido persistir a sessão do usuário no banco de dados. Usar um token JWT já cumpre o papel de validar a sessão do usuário.
Podemos simplesmente verificar se o token ainda é válido ao decodificá-lo e verificar se o seu prazo de validade não expirou ainda.
