### ISSUE TITLE
3. Ferramenta de Email

### ISSUE THREAD

**Issue by isamaues** [BrieflyPlanningPokerES23/BrieflyPlanningPoker#3]
Atualizar ferramenta de e-mail do node

- usado para recuperar a senha do usuário
- a api do google aparentemente mudou, com isso ficou deprecada a função de e-mail

Para fazer funcionar, precisa 

- [x] Analisar e estudar a viabilidade um novo provedor de email

- [x] Configurar  nova infraestrutura

- [x] Migrar código e variáveis de ambiente para novo provador

**Comment by jplukas** [comment]
Fixed in #29
