### ISSUE TITLE
4. Lembrete

### ISSUE THREAD

**Issue by isamaues** [BrieflyPlanningPokerES23/BrieflyPlanningPoker#4]
Lembrete  de votar para as pessoas não perderem o prazo de votação
(zap, sms,telegram, bot) - EMAIL

Precisamos entender melhor o caso de uso e quais sistemas queremos ter integração

**Comment by isamaues** [comment]
Ingrid acha que seria melhor notificações por e-mail por ser algo coorporativo, não invadir as plataformas privadas

**Comment by jplukas** [comment]
Closing for now
