### ISSUE TITLE
Definir horário de reunião e demais cerimônias

### ISSUE THREAD

**Issue by isamaues** [BrieflyPlanningPokerES23/BrieflyPlanningPoker#8]
Definir com que frequência vamos nos reunir (presencial ou remotamente)
[When2Meet](https://www.when2meet.com/?21393554-lA4wN)

**Comment by jplukas** [comment]
Precisamos definir isso o mais rápido possível. Ainda precisamos fazer um refinamento do backlog e definir o que vai ser feito em cada ciclo de desenvolvimento. Por favor usem o When2Meet para marcar os horários que vocês têm disponíveis.

**Comment by jplukas** [comment]
Definimos o horário como Sábados das 13-17h
